### ISSUE TITLE
项目下载完以后打开不能直接运行

### ISSUE THREAD

**Issue by liuzexin** [SpikeKing/WclPropertyFinder#1]
缺少什么工程文件是我打开方式不对？还是你上传的东西少了？

**Comment by SpikeKing** [comment]
应该是缺少配置的问题. 具体参考这个两篇文章.
配置项目: http://www.wangchenlong.org/2016/04/11/1604/111-rn-open-project/
环境: http://www.wangchenlong.org/2016/04/07/1604/071-rn-uiexplorer/

**Comment by SpikeKing** [comment]
不要紧张, 哈哈. RN是JS类工程, 需要Node支持.

**Comment by baoyachi** [comment]
请问你的个人网站是怎么搭的？

**Comment by SpikeKing** [comment]
Hexo + Next
